server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/
    schemas: book_service
    user: postgres
    password: 1234
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false